### ISSUE TITLE
Install issue -Blank Card

### ISSUE THREAD

**Issue by Cozzman2k** [ibBogdan/lovelace-htc-flipclock-weather#29]
I copied the files, added the resource, and dropped yaml code for card without too much issue but the card loads blank.  Console errors attached.  Network tab looks like its loaded the js cleanly.

Thanks for your help

![image](https://user-images.githubusercontent.com/123198679/213954489-c7997b5f-44bc-45ae-b519-e5a4feb2c620.png)
![image](https://user-images.githubusercontent.com/123198679/213954524-2b0c2668-24b8-449b-8067-a1456728905c.png)

**Comment by Cozzman2k** [comment]
Update to this, I removed the card code which was based on your dusk example and just used the simplest code you had in your examples and now it works.  However, the am_pm: makes the clock still 24hrs but has a "am" next to the hour when it should even be "PM" 

Whats does the Am/PM code look like?

**Comment by justinmheath2022** [comment]
Same issue here, Resources are loaded fine but the card is blank. any help appreciated

**Comment by justinmheath2022** [comment]
Ok I fixed my issue, I am in the US and had to install the NOAA Integration ( https://www.home-assistant.io/integrations/nws/) and the use the entity of (weather.kcsg_daynight)  "KCSG" is my local weather station as found here https://forecast.weather.gov

this took me a few hours to figure out and i hope this helps someone else

**Comment by Cozzman2k** [comment]
That did it, nice find.  Still can't get am/pm 12h clock function.

**Comment by justinmheath2022** [comment]
![image](https://user-images.githubusercontent.com/121302335/215218875-e6dd4ee6-4ca0-4688-9eef-4056763c921a.png)

**Comment by Cozzman2k** [comment]
I swear to God I tried that but you're right.  That fixed it.  Thank you.
